name: UltimateSkyWars
version: 1.0
main: me.CookieLuck.Main
author: CookieLuck
api: ["1.0.9"]

commands:
  usw:
    description: How to use the command.
    usage: /usw <args>
permissions:
  usw.join:
     descrption: Lets you join the game
     default: true
  usw.leave:
    descrption: Lets you leave the game
    default: true
  usw.saveworlds:
    descrption: Lets you save worlds
    default: op
  usw.create:
    descrption: Lets you create games
    default: op
  usw.setspawns:
    descrption: Lets you set spawns
    default: op
